# Begin Project
project:
  type: tutorial-template
# End Project

# Begin Website
website:
  title: "Generating and Evaluating Synthetic Data in R"
  page-footer:
    border: false
    center: "© 2026 Thom Volker. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0."
  repo-url: https://github.com/lmu-osc/synthetic-data-tutorial

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/synthetic-data-tutorial
          - text: Report a Bug
            href: https://github.com/lmu-osc/synthetic-data-tutorial/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - text: "Statistical Disclosure Control"
        href: sdc/index.qmd
      - text: "Synthetic Data: The General Idea"
        href: synthetic/index.qmd
      - text: "Generating Synthetic Data"
        href: generation/index.qmd
      - text: "Evaluating Synthetic Data Quality"
        href: evaluation/index.qmd
      - text: "Publishing and Using Synthetic Data"
        href: publishing/index.qmd
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
include-after-body:
  - file: footer/footer.html
# End Includes

# Begin Format
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
    toc: true
    code-overflow: wrap
    grid:
      sidebar-width: 300px
# End Format

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
